Repository octo-cli/octo-cli, pull requests merged in 2020-05, with the labels that each got.

#77 add script/release
  .github/workflows/release-tagger.yml
  .github/workflows/tag-releaser.yml
  script/release
Labels: enhancement

#78 dummy release
  .github/workflows/tag-releaser.yml
Labels: patch

#81 quick update to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: patch

#82 remove --token from help
  README.md
  internal/basecmd.go
Labels: enhancement

#86 fix new-routes-pr
  script/new-routes-pr
Labels: bug

#89 clean up help data for previews
  docs/operations.md
  internal/generated/cli.go
  internal/generator/swaggerparser/swaggerparser.go
  internal/generator/testdata/docs/operations.md
  internal/generator/testdata/generated/cli.go
Labels: enhancement

#91 update docs
  README.md
  docs/CONTRIBUTING.md
  docs/README.md
  docs/_sidebar.md
  docs/index.html
  readmegen.go
  script/update-docs
Labels: enhancement

#92 no symlinks for docs
  docs/CONTRIBUTING.md
  docs/README.md
  script/update-docs
Labels: bug

#94 remove commands from sidebar
  docs/_sidebar.md
Labels: bug

#96 README: simplify Homebrew instructions
  README.md
  docs/README.md
Labels: bug, docs

#98 rewrite readme intro
  README.md
  docs/README.md
Labels: docs, patch

#106 use common model for generation
  docs/unsupported.md
  go.mod
  go.sum
  internal/generator/codegen/builder.go
  internal/generator/docgen/docgen.go
  internal/generator/overrides/overrides.go
  internal/generator/supported/supported.go
  internal/generator/swaggerparser/swaggerparser.go
  internal/generator/testdata/docs/unsupported.md
  internal/generator/util/modelhelp.go
  internal/generator/util/supported.go
  internal/generator/util/types.go
  internal/generator/util/util.go
  internal/model/model.go
  internal/model/openapi/openapi.go
Labels: patch
